### ISSUE TITLE
切换协议仍然会出现code235

### ISSUE THREAD

**Issue by HatsuneMK00** [MrXiaoM/Aoki#11]
在Aoki上使用MACOS协议登录时出现了235，切换了协议到ANDROID_PHONE / ANDROID_PAD，并按照指引清除了所有数据，以及在官方客户端上登录了之后，仍然出现235.

不知道是否有什么解决办法？或是我哪里操作不正确？

**Comment by kagg886** [comment]
show your version, please

**Comment by HatsuneMK00** [comment]
Aoki 1.1.3, mirai 2.14.0. Is these enough or some more details are needed?

**Comment by MrXiaoM** [comment]
风控了，应该按照 [无法登录的临时解决处理方案](https://mirai.mamoe.net/topic/223) 寻找方法解决。  
风控是一个复杂的问题，并不由单一因素决定，风控问题不在 Aoki 的处理范围内，Aoki 仅保证可以尽可能地真实地模拟当前真实设备的设备信息，以及提供引导式的登录解决器。
