### ISSUE TITLE
新功能请求-生成konata框架的device.json

### ISSUE THREAD

**Issue by lepollo** [MrXiaoM/Aoki#14]
Konata是一个QQ机器人框架，其device.json跟mirai字段不一样，样本如下：
{
  "Model": {
    "Name": "Konata 947D9EE9",
    "Manufacturer": "Konata Project",
    "Imei": "44178756053474",
    "Imsi": "837167853702068",
    "BaseBand": "Konata.CORE.CAB7.1.0.REV",
    "CodeName": "REL"
  },
  "Display": {
    "Width": 1080,
    "Height": 1920
  },
  "System": {
    "Name": "Konata",
    "Type": "android",
    "Version": "11.0.1",
    "BootId": "457b0b1126db4650",
    "BootLoader": "Konata.CORE.8AD19155.BOOTLOADER_1_0",
    "AndroidId": "18b2bd9458ab4c56",
    "Incremental": "3d46096acc44092d",
    "InnerVersion": "Konata.CORE.USERDEBUG.11.0.1",
    "FingerPrint": "Konata/core/Konata:11.0.1/00580765:user/release-keys",
    "Guid": "aNx4F3PUykeEmASNjs3oRA=="
  },
  "Network": {
    "NetType": 2,
    "NetApn": "CMNET",
    "NetOperator": "China Mobile",
    "NetIpAddress": "AAAAAA==",
    "WifiMacAddress": "qrvM3e4=",
    "WifiSsid": "<Hidden SSID>",
    "WifiBssid": "qrvM3e4="
  }
}

**Comment by MrXiaoM** [comment]
invalid: 我不使用那个框架，你需要的话 PRs welcome.
