### ISSUE TITLE
希望尽快更新，fix-protocol-version已经到1.7.0了

### ISSUE THREAD

**Issue by SugarFatFree** [MrXiaoM/Aoki#15]
希望尽快更新App，fix-protocol-version已经到1.7.0了，同时希望自定义device.json功能尽快出来。

**Comment by Jimme** [comment]
同

**Comment by MrXiaoM** [comment]
目前仅会更新 fix-protocol-version 的部分功能。
拉取代码中的最新协议信息，添加从网络下载协议功能，添加本地文件修改协议功能。
将不会使用 fix-protocol-version 新版本中的 tlv544 提供器，而使用 lvyitian/tlv544_enc。

自定义 device.json 在写了。

**Comment by MrXiaoM** [comment]
device info 编辑器写好了。

**Comment by SugarFatFree** [comment]
> device info 编辑器写好了。

啥时候打包发布一个版本呀

**Comment by MrXiaoM** [comment]
> 啥时候打包发布一个版本呀

把协议信息更新功能写好后就发 1.2.1-pre2

**Comment by MrXiaoM** [comment]
安卓目标的 mirai 有 bug 导致无法发布，目前不会这么快发版，需要的可以先自己编译
