### ISSUE TITLE
账号导入bot文件夹后，mcl还是要提示登录。。

### ISSUE THREAD

**Issue by holygodly** [MrXiaoM/Aoki#17]
打扰一下大佬，小白想问下为啥用这个app导入账号信息到mcl的bot文件夹覆盖后，mcl还是提示要重新滑块登录呀。。找了一下午都没找到解决方法，麻烦大佬指点一下。。。
![image](https://github.com/MrXiaoM/Aoki/assets/41179861/972084d6-6309-46d4-b741-c95aec2aa5c1)
![image](https://github.com/MrXiaoM/Aoki/assets/41179861/cdf905da-e1dd-42a6-baf8-2a02c1985b30)

**Comment by holygodly** [comment]
![}Z0OT9X~IJZRTKU3DJE}PBK](https://github.com/MrXiaoM/Aoki/assets/41179861/aeb9e5ba-92cd-43c4-bb3a-75d6340bb763)
还有个没报错的，我在AutoLogin里设置的protocol也是ANDROID_WATCH，与app内一致，不知道为啥会无视我bots文件夹里的账号还让我重新登录。。
版本是照着您这个教程升到了v2.15.0-M1：https://mirai.mamoe.net/topic/2061/%E6%95%99%E7%A8%8B-%E7%94%A8mcl%E5%8D%87%E7%BA%A7mirai%E5%88%B0%E9%A2%84%E5%8F%91%E8%A1%8C%E7%89%88-%E6%93%8D%E4%BD%9C%E7%A4%BA%E4%BE%8B/2?_=1687769218687

**Comment by MrXiaoM** [comment]
不负责解决登录问题，登录问题请前往论坛
