### ISSUE TITLE
安卓平板版本现在为8.9.58，然后protocol的插件版本是1.9.4但是登录的时候报以下错误

### ISSUE THREAD

**Issue by nenemiku** [MrXiaoM/Aoki#18]
Login failed: Expected start of the object '{', but had 'EOF' instead at path: $
JSON input: .....et URL: [/login](https://github.com/login). If not click the link.
2023-07-12 09:24:21 E/console: kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '
{', but had 'EOF' instead at path: $
JSON input: .....et URL: [/login](https://github.com/login). If not click the link.
kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at pa
th: $
JSON input: .....et URL: [/login](https://github.com/login). If not click the link.

**Comment by MrXiaoM** [comment]
非 Aoki 问题
