### ISSUE TITLE
QQ手机协议登陆时提示版本过低

### ISSUE THREAD

**Issue by Pika-Lee** [MrXiaoM/Aoki#9]
如图所示

![Screenshot_20230301_154400_Aoki](https://user-images.githubusercontent.com/23114990/222293510-4e1432ff-dd80-4018-ae83-c965fba7f779.jpg)

//换成android_watch后正常

**Comment by MrXiaoM** [comment]
版本过低是因为你的账号或者ip被风控了。
风控等级 `code=45` > `code=237` > `code=235`。
